name: Compile and Test
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v5
    - name: Setup Rust
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
